name: InsolenceArmor
version: '${project.version}'
main: me.cabeca.insolencearmor.HiddenArmor
api-version: 26.2
authors: [ Cabeca ]
description: Let players hide their armor and show off their skins
depend: [ProtocolLib]
commands:
  hiddenarmor:
    description: "Main Hidden Armor command."
    aliases: [ha, armor]
  togglearmor:
    description: "Toggles armor visibility."
  togglepumpkin:
      description: "Toggles a fake pumpkin helmet appearance."
      usage: "/togglepumpkin <name> OR /togglepumpkin <player> <name>"